on:
  rss:
    url:
      - https://we-rss.0xn0p.org/feed/3285064611.xml
      - https://we-rss.0xn0p.org/feed/3938617593.xml
      - https://we-rss.0xn0p.org/feed/3281543765.xml
      - https://we-rss.0xn0p.org/feed/3276423214.xml
      - https://we-rss.0xn0p.org/feed/3217611549.xml
      - https://we-rss.0xn0p.org/feed/3922393753.xml
      - https://we-rss.0xn0p.org/feed/3863477301.xml
      - https://we-rss.0xn0p.org/feed/3562460013.xml
      - https://we-rss.0xn0p.org/feed/3201234304.xml
      - https://we-rss.0xn0p.org/feed/3244090624.xml
      - https://we-rss.0xn0p.org/feed/3086908177.xml
      - https://we-rss.0xn0p.org/feed/3258424782.xml
      - https://we-rss.0xn0p.org/feed/3897243887.xml
      - https://we-rss.0xn0p.org/feed/3572504738.xml
      - https://we-rss.0xn0p.org/feed/3863679550.xml
      - https://we-rss.0xn0p.org/feed/3219615681.xml
      - https://we-rss.0xn0p.org/feed/3514448686.xml
      - https://we-rss.0xn0p.org/feed/3924266231.xml
      - https://rss.0xn0p.org/zhihu/zhuanlan/c_1396461495899901955
      
jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@main
        with:
          url: ${{ secrets.CUBOX_API_SECRETS }}
          method: POST
          body: |
            {
              "type":"url",
              "content":"${{ on.rss.outputs.link }}", 
              "title": "${{ on.rss.outputs.title }}"
            }
