on:
  rss:
    url:
      - https://cdn.werss.weapp.design/api/v1/feeds/2705d88b-d31d-4d2c-b3bc-f338095c0165.xml
      - https://cdn.werss.weapp.design/api/v1/feeds/dc1a5b10-9f74-4802-8cb2-834ef78d609c.xml
      - https://cdn.werss.weapp.design/api/v1/feeds/ad4ac158-3f97-4fb0-be12-5a65f630db59.xml
      - https://cdn.werss.weapp.design/api/v1/feeds/daedb361-8163-4bfa-b2de-5ea515b2fd5b.xml
      - https://cdn.werss.weapp.design/api/v1/feeds/a95adaff-594d-47c6-9bf7-9949c16c6328.xml
      - https://cdn.werss.weapp.design/api/v1/feeds/00c3d618-c911-4021-bc7b-cca681bf2ae3.xml
      - https://cdn.werss.weapp.design/api/v1/feeds/c35f72f6-7bb7-422a-82a8-eaff5485660a.xml
      - https://cdn.werss.weapp.design/api/v1/feeds/60461805-4009-4e0f-adb3-a70430c6c16e.xml
      - https://cdn.werss.weapp.design/api/v1/feeds/0f3bff2c-c38d-4836-aa27-e852dc5e83d6.xml
      - https://cdn.werss.weapp.design/api/v1/feeds/0116d07f-4546-4802-95db-76f4d4369dc2.xml
      - https://cdn.werss.weapp.design/api/v1/feeds/9737da14-9af3-4242-8e01-ac841cf7949d.xml
      - https://cdn.werss.weapp.design/api/v1/feeds/89616726-e313-4132-8a20-3b0c719c18aa.xml
      - https://cdn.werss.weapp.design/api/v1/feeds/877e20ea-9ddb-4dae-be85-1a30d0ea28ee.xml
      - https://cdn.werss.weapp.design/api/v1/feeds/b913813e-c929-447e-9d1a-a515c54823c5.xml
      - https://cdn.werss.weapp.design/api/v1/feeds/f017504b-0bb6-477c-bb4f-8ff4cfdfe888.xml
      - https://cdn.werss.weapp.design/api/v1/feeds/a8686f81-9218-4146-bc96-605db0a682a5.xml
      - https://cdn.werss.weapp.design/api/v1/feeds/c2eb6f5c-f629-4301-ab87-20d7f111552e.xml
      - https://rss.0xn0p.org/zhihu/zhuanlan/c_1396461495899901955
      
jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@main
        with:
          url: ${{ secrets.CUBOX_API_SECRETS }}
          method: POST
          body: |
            {
              "type":"url",
              "content":"${{ on.rss.outputs.link }}", 
              "title": "${{ on.rss.outputs.title }}"
            }
